name: skyclock
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.3
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/morning.jpg
    - assets/afternoon.jpg
    - assets/evening.jpg
    - assets/night.jpg
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png